#ifndef NOUGHTS_AND_CROSSES_COLOURS_H
#define NOUGHTS_AND_CROSSES_COLOURS_H

const Uint8 OFF_WHITE = 0xF2;
const Uint8 OFF_BLACK = 0x22;
const Uint8 LIGHT_GREY = 0xD1;
const Uint8 DARK_GREY = 0x9B;

#endif //NOUGHTS_AND_CROSSES_COLOURS_H
