#ifndef NOUGHTS_AND_CROSSES_CONSTANTS_H
#define NOUGHTS_AND_CROSSES_CONSTANTS_H

#include <SDL_rect.h>

const int SCREEN_WIDTH = 1280;
const int SCREEN_HEIGHT = 720;

const int GRID_SIZE = 9;

const SDL_Point GRID_OFFSET = {20, 20 };
const int GRID_LENGTH = 630;

#endif //NOUGHTS_AND_CROSSES_CONSTANTS_H
